Add unicorn init.d upgrade command

diff --git a/unicorn/unicorn.init.d.erb b/unicorn/unicorn.init.d.erb
--- a/unicorn/unicorn.init.d.erb
+++ b/unicorn/unicorn.init.d.erb
@@ -48,9 +48,31 @@ force-stop)
   sig TERM && exit 0
   echo >&2 "Not running"
   ;;
-restart)
-  mv $PID $old_pid && echo old pid moved && export $ENV_OPTS && $CMD && echo started ok && exit 0
-  echo >&2 "!!!! Something went wrong, trying to start anyway"
+restart|reload)
+  sig HUP && echo reloaded OK && exit 0
+  echo >&2 "Couldn't reload, starting '$CMD' instead"
+  export $ENV_OPTS
+  $CMD
+  ;;
+upgrade)
+  if sig USR2 && sleep 2 && sig 0 && oldsig QUIT
+  then
+    n=$TIMEOUT
+    while test -s $old_pid && test $n -ge 0
+    do
+      printf '.' && sleep 1 && n=$(( $n - 1 ))
+    done
+    echo
+
+    if test $n -lt 0 && test -s $old_pid
+    then
+      echo >&2 "$old_pid still exists after $TIMEOUT seconds"
+      exit 1
+    fi
+    exit 0
+  fi
+  echo >&2 "Couldn't upgrade, starting '$CMD' instead"
+  export $ENV_OPTS
   $CMD
   ;;
 kill_worker)
